version: "3"
services:
    postgres:
        image: "postgres"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=rngtjeb2
            - POSTGRES_DB=postgres
        ports:
            - "5432:5432"
        volumes:
            - /postgres-data:/var/lib/postgresql/data

    pgadmin-compose:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "postgres"
            PGADMIN_DEFAULT_PASSWORD: "rngtjeb2"
        ports:
            - "54321:80"
        depends_on:
            - postgres

    worker:
        build: ./src
        command: npm start
        ports:
            - "9730:9730"
        volumes:
            - ./src/:/src/
            - /src/node_modules
